### ISSUE TITLE
.NET Coding Pack fails to install the .NET extension pack in VS Code 

### ISSUE THREAD

**Issue by sfoslund** [dotnet/vscode-dotnet-pack#23]
---
**Issue moved from dotnet/installer#11977**
- Please respond to @sana-ajani.

---

_From @sana-ajani on Monday, September 13, 2021 3:15:15 PM_

Originally filed by @profix898 in the microsoft/vscode repo. 
---
I have downloaded the '.NET Coding Pack for VS Code' (https://code.visualstudio.com/learn/educators/installers#_net-coding-pack) installer. VS Code (step 1) and the .NET SDK (step 2) get installed correctly. However, the third step, which is supposed to install the '.NET Extension Pack' extension into the newly installed VS Code, fails. The error message simply says: "Failed to install .NET Extension Pack" (see screenshot).
It looks like you have to launch VS Code once, so that it registers itself with Windows as the default program for VS Code extension packages. After that you can at least proceed manually.

Obviously, the .NET Coding Pack is meant for new .NET users to get started. Due to the above problem that turns out a pretty bad experience ...

![image](https://user-images.githubusercontent.com/9721254/133110211-b0f13750-5ce2-44d8-98ad-9dcd0ab65dd8.png)

cc @mikadumont

**Comment by sfoslund** [comment]
@profix898 thanks for filing an issue, can you please provide the log file located at $TMPDIR/vscode-dotnet-installer/log.txt? Also, what OS are you using and what version of the education pack installer? When was this issue originally filed?

**Comment by profix898** [comment]
I filed this originally 2 weeks ago on Windows 10 (build 10.0.19043). Since I don't remember the exact installer version, I just downloaded the latest bits from https://code.visualstudio.com/learn/educators/installers#_net-coding-pack, which is now v1.0.0, and the problem seems to be resolved now.
Thanks anyway.

**Comment by sfoslund** [comment]
Awesome, yes, this looks like a known issue we had with an earlier build, but was fixed before 1.0. Closing this as fixed...
